// ======================================================================
// \title  ByteStreamSendPortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for ByteStreamSend port
// ======================================================================

#ifndef Drv_ByteStreamSendPortAc_HPP
#define Drv_ByteStreamSendPortAc_HPP

#include <cstdio>
#include <cstring>

#include "Drv/ByteStreamDriverModel/SendStatusEnumAc.hpp"
#include "FpConfig.hpp"
#include "Fw/Buffer/Buffer.hpp"
#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Types/StringType.hpp"

namespace Drv {

  //! Input ByteStreamSend port
  class InputByteStreamSendPort :
    public Fw::InputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE =
          Fw::Buffer::SERIALIZED_SIZE
      };

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The port callback function type
      typedef Drv::SendStatus (*CompFuncPtr)(
        Fw::PassiveComponentBase* callComp,
        NATIVE_INT_TYPE portNum,
        Fw::Buffer& sendBuffer
      );

    public:

      // ----------------------------------------------------------------------
      // Input Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      InputByteStreamSendPort();

      //! Initialization function
      void init();

      //! Register a component
      void addCallComp(
          Fw::PassiveComponentBase* callComp, //!< The containing component
          CompFuncPtr funcPtr //!< The port callback function
      );

      //! Invoke a port interface
      Drv::SendStatus invoke(Fw::Buffer& sendBuffer);

    private:

#if FW_PORT_SERIALIZATION == 1

      //! Invoke the port with serialized arguments
      Fw::SerializeStatus invokeSerial(Fw::SerializeBufferBase& _buffer);

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the port callback function
      CompFuncPtr m_func;

  };

  //! Output ByteStreamSend port
  class OutputByteStreamSendPort :
    public Fw::OutputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Output Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      OutputByteStreamSendPort();

      //! Initialization function
      void init();

      //! Register an input port
      void addCallPort(
          InputByteStreamSendPort* callPort //!< The input port
      );

      //! Invoke a port interface
      Drv::SendStatus invoke(Fw::Buffer& sendBuffer);

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the input port
      InputByteStreamSendPort* m_port;

  };

}

#endif
