// ======================================================================
// \title  GpioWritePortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for GpioWrite port
// ======================================================================

#include "F-Prime/Drv/GpioDriverPorts/GpioWritePortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/StringUtils.hpp"

namespace Drv {

  namespace {

    // ----------------------------------------------------------------------
    // Port buffer class
    // ----------------------------------------------------------------------

    class GpioWritePortBuffer : public Fw::SerializeBufferBase {

      public:

        NATIVE_UINT_TYPE getBuffCapacity() const {
          return InputGpioWritePort::SERIALIZED_SIZE;
        }

        U8* getBuffAddr() {
          return m_buff;
        }

        const U8* getBuffAddr() const {
          return m_buff;
        }

      private:

        U8 m_buff[InputGpioWritePort::SERIALIZED_SIZE];

    };

  }

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputGpioWritePort ::
    InputGpioWritePort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputGpioWritePort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputGpioWritePort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  void InputGpioWritePort ::
    invoke(const Fw::Logic& state)
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, state);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputGpioWritePort ::
    invokeSerial(Fw::SerializeBufferBase& _buffer)
  {
    Fw::SerializeStatus _status;

#if FW_PORT_SERIALIZATION == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    Fw::Logic state;
    _status = _buffer.deserialize(state);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    this->m_func(this->m_comp, this->m_portNum, state);

    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputGpioWritePort ::
    OutputGpioWritePort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputGpioWritePort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputGpioWritePort ::
    addCallPort(InputGpioWritePort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  void OutputGpioWritePort ::
    invoke(const Fw::Logic& state)
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

#if FW_PORT_SERIALIZATION
    FW_ASSERT((this->m_port != nullptr) || (this->m_serPort != nullptr));

    if (this->m_port != nullptr) {
      this->m_port->invoke(state);
    }
    else {
      Fw::SerializeStatus _status;
      GpioWritePortBuffer _buffer;

      _status = _buffer.serialize(state);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = this->m_serPort->invokeSerial(_buffer);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));
    }
#else
    FW_ASSERT(this->m_port != nullptr);
    this->m_port->invoke(state);
#endif
  }

}
