// ======================================================================
// \title  CmdSequencer_FileReadStageEnumAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for CmdSequencer_FileReadStage enum
// ======================================================================

#ifndef Svc_CmdSequencer_CmdSequencer_FileReadStageEnumAc_HPP
#define Svc_CmdSequencer_CmdSequencer_FileReadStageEnumAc_HPP

#include "FpConfig.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace Svc {

  //! The stage of the file read operation
  class CmdSequencer_FileReadStage :
    public Fw::Serializable
  {

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The serial representation type
      typedef I32 SerialType;

      //! The raw enum type
      enum T {
        READ_HEADER = 0,
        READ_HEADER_SIZE = 1,
        DESER_SIZE = 2,
        DESER_NUM_RECORDS = 3,
        DESER_TIME_BASE = 4,
        DESER_TIME_CONTEXT = 5,
        READ_SEQ_CRC = 6,
        READ_SEQ_DATA = 7,
        READ_SEQ_DATA_SIZE = 8,
      };

      //! For backwards compatibility
      typedef T t;

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representation
        SERIALIZED_SIZE = sizeof(SerialType),
        //! The number of enumerated constants
        NUM_CONSTANTS = 9,
      };

    public:

      // ----------------------------------------------------------------------
      // Constructors
      // ----------------------------------------------------------------------

      //! Constructor (default value of READ_HEADER)
      CmdSequencer_FileReadStage()
      {
        this->e = READ_HEADER;
      }

      //! Constructor (user-provided value)
      CmdSequencer_FileReadStage(
          const T e //!< The raw enum value
      )
      {
        this->e = e;
      }

      //! Copy constructor
      CmdSequencer_FileReadStage(
          const CmdSequencer_FileReadStage& obj //!< The source object
      )
      {
        this->e = obj.e;
      }

    public:

      // ----------------------------------------------------------------------
      // Operators
      // ----------------------------------------------------------------------

      //! Copy assignment operator (object)
      CmdSequencer_FileReadStage& operator=(
          const CmdSequencer_FileReadStage& obj //!< The source object
      );

      //! Copy assignment operator (raw enum)
      CmdSequencer_FileReadStage& operator=(
          T e //!< The enum value
      );

      //! Conversion operator
      operator T() const
      {
        return this->e;
      }

      //! Equality operator
      bool operator==(T e) const
      {
        return this->e == e;
      }

      //! Inequality operator
      bool operator!=(T e) const
      {
        return !(*this == e);
      }

#ifdef BUILD_UT

      //! Ostream operator
      friend std::ostream& operator<<(
          std::ostream& os, //!< The ostream
          const CmdSequencer_FileReadStage& obj //!< The object
      );

#endif

    public:

      // ----------------------------------------------------------------------
      // Member functions
      // ----------------------------------------------------------------------

      //! Check raw enum value for validity
      bool isValid() const;

      //! Serialize raw enum value to SerialType
      Fw::SerializeStatus serialize(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      ) const;

      //! Deserialize raw enum value from SerialType
      Fw::SerializeStatus deserialize(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      );

#if FW_SERIALIZABLE_TO_STRING || BUILD_UT

      //! Convert enum to string
      void toString(
          Fw::StringBase& sb //!< The StringBase object to hold the result
      ) const;

#endif

    public:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The raw enum value
      T e;

  };

}

#endif
