// ======================================================================
// \title  ByteStreamPollPortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for ByteStreamPoll port
// ======================================================================

#ifndef Drv_ByteStreamPollPortAc_HPP
#define Drv_ByteStreamPollPortAc_HPP

#include <cstdio>
#include <cstring>

#include "Drv/ByteStreamDriverModel/PollStatusEnumAc.hpp"
#include "FpConfig.hpp"
#include "Fw/Buffer/Buffer.hpp"
#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Types/StringType.hpp"

namespace Drv {

  //! Input ByteStreamPoll port
  class InputByteStreamPollPort :
    public Fw::InputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE =
          Fw::Buffer::SERIALIZED_SIZE
      };

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The port callback function type
      typedef Drv::PollStatus (*CompFuncPtr)(
        Fw::PassiveComponentBase* callComp,
        NATIVE_INT_TYPE portNum,
        Fw::Buffer& pollBuffer
      );

    public:

      // ----------------------------------------------------------------------
      // Input Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      InputByteStreamPollPort();

      //! Initialization function
      void init();

      //! Register a component
      void addCallComp(
          Fw::PassiveComponentBase* callComp, //!< The containing component
          CompFuncPtr funcPtr //!< The port callback function
      );

      //! Invoke a port interface
      Drv::PollStatus invoke(Fw::Buffer& pollBuffer);

    private:

#if FW_PORT_SERIALIZATION == 1

      //! Invoke the port with serialized arguments
      Fw::SerializeStatus invokeSerial(Fw::SerializeBufferBase& _buffer);

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the port callback function
      CompFuncPtr m_func;

  };

  //! Output ByteStreamPoll port
  class OutputByteStreamPollPort :
    public Fw::OutputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Output Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      OutputByteStreamPollPort();

      //! Initialization function
      void init();

      //! Register an input port
      void addCallPort(
          InputByteStreamPollPort* callPort //!< The input port
      );

      //! Invoke a port interface
      Drv::PollStatus invoke(Fw::Buffer& pollBuffer);

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the input port
      InputByteStreamPollPort* m_port;

  };

}

#endif
