// ======================================================================
// \title  Ports_RateGroupsEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Ports_RateGroups enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "SystemRef/Top/Ports_RateGroupsEnumAc.hpp"

namespace SystemRef {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  Ports_RateGroups& Ports_RateGroups ::
    operator=(const Ports_RateGroups& obj)
  {
    this->e = obj.e;
    return *this;
  }

  Ports_RateGroups& Ports_RateGroups ::
    operator=(T e)
  {
    this->e = e;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const Ports_RateGroups& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool Ports_RateGroups ::
    isValid() const
  {
    return ((e >= rateGroup1) && (e <= rateGroup1));
  }

  Fw::SerializeStatus Ports_RateGroups ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus Ports_RateGroups ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING || BUILD_UT

  void Ports_RateGroups ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case rateGroup1:
        s = "rateGroup1";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%d)", s.toChar(), e);
  }

#endif

}
