// ======================================================================
// \title  SendFileStatusEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for SendFileStatus enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Svc/FileDownlinkPorts/SendFileStatusEnumAc.hpp"

namespace Svc {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  SendFileStatus& SendFileStatus ::
    operator=(const SendFileStatus& obj)
  {
    this->e = obj.e;
    return *this;
  }

  SendFileStatus& SendFileStatus ::
    operator=(T e)
  {
    this->e = e;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const SendFileStatus& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool SendFileStatus ::
    isValid() const
  {
    return ((e >= STATUS_OK) && (e <= STATUS_BUSY));
  }

  Fw::SerializeStatus SendFileStatus ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus SendFileStatus ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING || BUILD_UT

  void SendFileStatus ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case STATUS_OK:
        s = "STATUS_OK";
        break;
      case STATUS_ERROR:
        s = "STATUS_ERROR";
        break;
      case STATUS_INVALID:
        s = "STATUS_INVALID";
        break;
      case STATUS_BUSY:
        s = "STATUS_BUSY";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%d)", s.toChar(), e);
  }

#endif

}
