// ======================================================================
// \title  ActiveLogger_EnabledEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for ActiveLogger_Enabled enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Svc/ActiveLogger/ActiveLogger_EnabledEnumAc.hpp"

namespace Svc {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  ActiveLogger_Enabled& ActiveLogger_Enabled ::
    operator=(const ActiveLogger_Enabled& obj)
  {
    this->e = obj.e;
    return *this;
  }

  ActiveLogger_Enabled& ActiveLogger_Enabled ::
    operator=(T e)
  {
    this->e = e;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const ActiveLogger_Enabled& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool ActiveLogger_Enabled ::
    isValid() const
  {
    return ((e >= ENABLED) && (e <= DISABLED));
  }

  Fw::SerializeStatus ActiveLogger_Enabled ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus ActiveLogger_Enabled ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING || BUILD_UT

  void ActiveLogger_Enabled ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case ENABLED:
        s = "ENABLED";
        break;
      case DISABLED:
        s = "DISABLED";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%d)", s.toChar(), e);
  }

#endif

}
