// ======================================================================
// \title  DataBufferPortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for DataBuffer port
// ======================================================================

#ifndef Drv_DataBufferPortAc_HPP
#define Drv_DataBufferPortAc_HPP

#include <cstdio>
#include <cstring>

#include "Drv/DataTypes/DataBuffer.hpp"
#include "FpConfig.hpp"
#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/StringType.hpp"

namespace Drv {

  //! Input DataBuffer port
  //! Data Buffer Port
  class InputDataBufferPort :
    public Fw::InputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE =
          Drv::DataBuffer::SERIALIZED_SIZE
      };

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The port callback function type
      typedef void (*CompFuncPtr)(
        Fw::PassiveComponentBase* callComp,
        NATIVE_INT_TYPE portNum,
        Drv::DataBuffer& buff
      );

    public:

      // ----------------------------------------------------------------------
      // Input Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      InputDataBufferPort();

      //! Initialization function
      void init();

      //! Register a component
      void addCallComp(
          Fw::PassiveComponentBase* callComp, //!< The containing component
          CompFuncPtr funcPtr //!< The port callback function
      );

      //! Invoke a port interface
      void invoke(
          Drv::DataBuffer& buff //!< A data buffer
      );

    private:

#if FW_PORT_SERIALIZATION == 1

      //! Invoke the port with serialized arguments
      Fw::SerializeStatus invokeSerial(Fw::SerializeBufferBase& _buffer);

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the port callback function
      CompFuncPtr m_func;

  };

  //! Output DataBuffer port
  //! Data Buffer Port
  class OutputDataBufferPort :
    public Fw::OutputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Output Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      OutputDataBufferPort();

      //! Initialization function
      void init();

      //! Register an input port
      void addCallPort(
          InputDataBufferPort* callPort //!< The input port
      );

      //! Invoke a port interface
      void invoke(
          Drv::DataBuffer& buff //!< A data buffer
      );

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the input port
      InputDataBufferPort* m_port;

  };

}

#endif
